run-example:
	@go run . < example.txt

run-example-2:
	@go run . < example-two.txt

run-example-mini:
	@go run . < example-mini.txt

run-example-tiny:
	@go run . < example-tiny.txt

run-example-zigzag:
	@go run . < example-zigzag.txt

run-input:
	@go run . < input.txt
